services:
    web:
        build: .
        ports:
            - "3001:3001"
        environment:
            - NODE_ENV=production
            - PORT=3001
        volumes:
            - .:/app
            - /app/node_modules
            - /app/.next
        command: npm start
